#!/bin/bash
usage(){
	fmt <<EOF
DESCRIPTION
	Prettify source files in a Standard Ebooks ebook source directory, including canonicalizing XML and minifying SVGs.  Note that this only prettifies the source code; it doesn't perform typography changes.

USAGE
	clean [-v,--verbose] DIRECTORY [DIRECTORY...]
		DIRECTORY is the source directory, which must contain DIRECTORY/src/.
EOF
	exit
}
die(){ printf "Error: ${1}\n" 1>&2; exit 1; }
require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
if [ $# -eq 1 ]; then if [ "$1" = "--help" -o "$1" = "-h" ]; then usage; fi fi
#End boilerplate

#Check for dependencies
require "svgcleaner-cli" "Try: sudo apt-get install svgcleaner"
require "recode" "Try: sudo apt-get install recode"
require "xml2asc" "Try: sudo apt-get install html-xml-utils"

if [ $# -eq 0 ]; then
	usage
fi

verbose="false"
dirs=""

while [ $# -gt 0 ]
do
	case "$1" in
		-v|--verbose)
			verbose="true"
		;;
		*)
			dirs=$(printf "%s\n%s" "${dirs}" "$1")
		;;
	esac
	shift
done

printf "%s\n" "${dirs}" | while IFS= read -r i;
do
	if [ "${i}" = "" ]; then
		continue
	fi
	
	srcDir="$(realpath "${i%/}")"

	if [ ! -d "${srcDir}/src" ]; then
		die "${srcDir} does't look like a Standard Ebooks ebook source directory."
	fi

	if [ "${verbose}" = "true" ]; then
		printf "Cleaning %s ..." "${srcDir}"
	fi

	#This huge list of flags emulates `svgcleaner-cli --type-complete`, but WITHOUT the paths options, which usually messes things up.
	#Disabled for now because it screws up our nicely formatted simple svgs
	#find "${srcDir}" -iname "*.svg" -type f -exec svgcleaner-cli "{}" "{}" --remove-comments --remove-unused-defs --remove-nonsvg-elts --remove-metadata-elts --remove-inkscape-elts --remove-sodipodi-elts --remove-ai-elts --remove-corel-elts --remove-msvisio-elts --remove-sketch-elts --remove-invisible-elts --remove-empty-containers --remove-duplicated-defs --remove-outside-elts --equal-elts-to-use --ungroup-containers --merge-gradients --remove-unreferenced-ids --trim-ids --remove-notappl-atts --remove-default-atts --remove-inkscape-atts --remove-sodipodi-atts --remove-ai-atts --remove-corel-atts --remove-msvisio-atts --remove-sketch-atts --remove-stroke-props --remove-fill-props --remove-unused-xlinks --join-style-atts --simplify-transform-matrix --apply-transforms-to-defs --apply-transforms-to-shapes --colors-to-rrggbb --rrggbb-to-rgb --convert-basic-shapes --create-viewbox --apply-transforms-to-defs --sort-defs > /dev/null 2>&1 \;

	#Set xmllint to use tab indentation.
	export XMLLINT_INDENT=$(printf "\t")

	#Epub3 doesn't allow named entities, so convert them to their unicode equivalents
	#First we use xml2asc to convert *all* special characters to named entities.
	#Then recode converts named entities to unicode.
	find "${srcDir}" -iname "*.xhtml" -type f -exec sh -c "xml2asc < "{}" | recode HTML | sed \"s/&/&amp;/g\" > /tmp/tmp.xhtml; mv /tmp/tmp.xhtml "{}"" \;

	#Clean files with xmllint.
	#The --c14n flag removes the XML declaration, so we re-add it before formatting.  Otherwise we get problems.
	find "${srcDir}" -iname "*.xhtml" -type f -exec sh -c "xmllint --c14n "{}" | (printf '%s\n' '<?xml version=\"1.0\" encoding=\"UTF-8\"?>' && cat) | xmllint --output "{}" --format -" \;
	find "${srcDir}" \( -iname "*.svg" -o -iname "*.opf" -o -iname "*.xml" \) -type f -exec sh -c "xmllint --c14n "{}" | (printf '%s\n' '<?xml version=\"1.0\" encoding=\"UTF-8\"?>' && cat) | xmllint --output "{}" --format -" \;

	#Add trailing newlines to files that don't have one.
	find "${srcDir}" \( -iname "*.xhtml" -o -iname "*.svg" -o -iname "*.css" -o -iname "*.opf" -o -iname "*.xml" \) -type f -exec sed -i -e '$a\' "{}" \;

	if [ "${verbose}" = "true" ]; then
		printf "%s\n" " OK"
	fi
done
