#!/usr/bin/env python3

import argparse
import sys
import roman
import se


def main():
	parser = argparse.ArgumentParser(description="Convert a decimal number to a Roman numeral.")
	parser.add_argument("-n", "--no-newline", dest="newline", action="store_false", help="don't end output with a newline")
	parser.add_argument("numbers", metavar="INTEGER", nargs="*", help="an integer")
	args = parser.parse_args()

	lines = []

	if not sys.stdin.isatty():
		for line in sys.stdin:
			lines.append(line.rstrip("\n"))

	for line in args.numbers:
		lines.append(line)

	for line in lines:
		if not line.isdigit():
			se.print_error("Not a digit: {}".format(line))
			exit(1)

		if args.newline:
			print(roman.toRoman(int(line)))
		else:
			print(roman.toRoman(int(line)), end="")


if __name__ == "__main__":
	main()
