#!/usr/bin/env python3

import argparse
import os
import sys
import zipfile
import magic

def main():
	parser = argparse.ArgumentParser(description="Extract an EPUB, MOBI, or AZW3 ebook into ./FILENAME.extracted/ or a target directory.")
	parser.add_argument("-v", "--verbose", action="store_true", help="increase output verbosity")
	parser.add_argument("-d", "--destination", type=str, help="a target directory to extract into")
	parser.add_argument("targets", metavar="TARGET", nargs="+", help="an EPUB, MOBI, or AZW3 file")
	args = parser.parse_args()

	for target in args.targets:
		target = os.path.abspath(target)

		if args.verbose:
			print("Processing {} ...".format(target), end="", flush=True)

		if args.destination is None:
			extracted_path = os.path.basename(target) + ".extracted"
		else:
			extracted_path = args.destination

		if os.path.exists(extracted_path):
			print("Error: Directory already exists: {}".format(extracted_path), file=sys.stderr)
			exit(1)

		mime_type = magic.from_file(target)

		if "Mobipocket E-book" in mime_type:
			#TODO
			pass
		elif "EPUB document" in mime_type:
			with zipfile.ZipFile(target, "r") as file:
				file.extractall(extracted_path)
		else:
			print("Error: Couldn't understand file type: {}".format(mime_type), file=sys.stderr)
			exit(1)

		if args.verbose:
			print(" OK")

if __name__ == "__main__":
	main()
