#!/bin/bash

usage(){
	fmt <<EOF
DESCRIPTION
	Generate the `words` file used by the `modernize-hyphenation` script and print to standard output.

USAGE
	generate-words

EOF
	exit
}
die(){ printf "Error: ${1}\n" 1>&2; exit 1; }
require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
if [ $# -eq 1 ]; then if [ "$1" = "--help" -o "$1" = "-h" ]; then usage; fi fi
#End boilerplate

require "wn" "Try: apt-get install wordnet"

if [ ! -f "/usr/share/dict/american-english-large" ]; then
	die "American word list is not installed. Try: apt-get install wamerican-large"
fi

if [ ! -f "/usr/share/dict/british-english-large" ]; then
	die "British word list is not installed. Try: apt-get install wbritish-large"
fi

#Combine the American and British English word lists
#Remove duplicates and sort
#Remove words that are 3 letters or less (highlighy unlikely to be old-timey compounds)
#Remove words not in the WordNet word list

cat "/usr/share/dict/american-english-large" "/usr/share/dict/british-english-large" | sort -u | sed --regexp-extended "/^[a-zA-Z]{1,3}\$/d" |
while read word; do
	wn "$word" | grep --quiet "Information available for"
	if [ $? -eq 0 ]; then
		echo "$word"
	fi
done
