#!/usr/bin/env python3

import argparse
import os
import se
import se.linter

def main():
	parser = argparse.ArgumentParser(description="Check for various Standard Ebooks style errors.")
	parser.add_argument("-v", "--verbose", action="store_true", help="increase output verbosity")
	parser.add_argument("directories", metavar="DIRECTORY", nargs="+", help="a Standard Ebooks source directory")
	args = parser.parse_args()

	script_directory = os.path.dirname(os.path.realpath(__file__))

	for directory in args.directories:
		if args.verbose:
			print("Processing {} ...".format(directory), end="", flush=True)

		messages = se.linter.lint(directory, script_directory)

		if messages and not args.verbose:
			print("{}:".format(directory))

		if messages and args.verbose:
			print("")

		for message in messages:
			if message.startswith(" "):
				se.print_line_after_warning(message[1:], True)
			else:
				se.print_warning(message, True)

		if not messages and args.verbose:
			print(" OK")


if __name__ == "__main__":
	main()
