#!/bin/bash
usage(){
	fmt <<EOF
DESCRIPTION
	Convert a fragment of MathML into a transparent PNG. Output is saved to the specified filename.

USAGE
	mathml2png -o OUTPUT-FILENAME FRAGMENT
		FRAGMENT is a fragment of MathML. For example: <math><mn>2</mn></math>

EOF
	exit
}
die(){ printf "Error: %s\n" "${1}" 1>&2; exit 1; }
require(){ command -v "$1" > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
if [ $# -eq 1 ]; then if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then usage; fi fi
# End boilerplate

require "convert" "Try: apt install imagemagick"
require "firefox" "Try: apt install firefox"

if [ $# -ne 3 ]; then
	usage
fi

if pgrep "firefox" &> /dev/null; then
	die "firefox is required to process MathML, but firefox is currently running. Close all instances of firefox and try again."
fi

echo "<!doctype html><html><head><meta charset=\"utf-8\"><title>MathML fragment</title></head><body>${3}</body></html>" > /tmp/mathml-fragment.html

firefox -screenshot /tmp/mathml.png file:///tmp/mathml-fragment.html &> /dev/null

convert /tmp/mathml.png -fuzz 10% -transparent white -trim "${2}"
