#!/usr/bin/env python3

import argparse
import math
import sys

def get_ordinal(number):
	number = int(number)
	return "%d%s" % (number, "tsnrhtdd"[(math.floor(number / 10) % 10 != 1) * (number % 10 < 4) * number % 10::4])

def main():
	parser = argparse.ArgumentParser(description="Print the ordinal for one or more integers.")
	parser.add_argument("-n", "--no-newline", dest="newline", action="store_false", help="don't end output with a newline")
	parser.add_argument("numbers", metavar="NUMBER", nargs="*", help="an integer")
	args = parser.parse_args()

	lines = []

	if not sys.stdin.isatty():
		for line in sys.stdin:
			lines.append(line.rstrip("\n"))

	for line in args.numbers:
		lines.append(line)

	for line in lines:
		if not line.isdigit():
			print("Error: Not a digit: {}".format(line), file=sys.stderr)
			exit(1)

		if args.newline:
			print(get_ordinal(line))
		else:
			print(get_ordinal(line), end="")

if __name__ == "__main__":
	main()
