#!/usr/bin/env python3

import argparse
import math

def main():
	parser = argparse.ArgumentParser(description="Print the ordinal for one or more integers.")
	parser.add_argument("numbers", metavar="NUMBER", nargs="+", help="An integer.")
	args = parser.parse_args()

	for number in args.numbers:
		number = int(number)
		print("%d%s" % (number, "tsnrhtdd"[(math.floor(number / 10) % 10 != 1) * (number % 10 < 4) * number % 10::4]))

if __name__ == "__main__":
	main()
