#!/usr/bin/env python3

import sys
import argparse
import se
from se.se_epub import SeEpub


def main() -> int:
	parser = argparse.ArgumentParser(description="Print <manifest> and <spine> tags to standard output for the given Standard Ebooks source directory, for use in that directory’s content.opf.")
	parser.add_argument("-m", "--manifest", action="store_false", help="only print the manifest")
	parser.add_argument("-s", "--spine", action="store_false", help="only print the spine")
	parser.add_argument("directory", metavar="DIRECTORY", help="a Standard Ebooks source directory")
	args = parser.parse_args()

	try:
		se_epub = SeEpub(args.directory)
	except se.SeException as ex:
		se.print_error(ex)
		return ex.code

	if args.spine:
		print(se_epub.generate_manifest())

	if args.manifest:
		print(se_epub.generate_spine())

	return 0


if __name__ == "__main__":
	sys.exit(main())
