#!/usr/bin/env python3

import argparse
import os
import se
from se.se_epub import SeEpub


def main():
	parser = argparse.ArgumentParser(description="Recompose a Standard Ebooks source directory into a single HTML5 file, and print to standard output.")
	parser.add_argument("directory", metavar="DIRECTORY", help="a Standard Ebooks source directory")
	args = parser.parse_args()

	try:
		se_epub = SeEpub(args.directory, os.path.dirname(os.path.realpath(__file__)))
		print(se_epub.recompose())
	except (OSError, se.SeError) as ex:
		se.print_error(ex)
		exit(1)


if __name__ == "__main__":
	main()
