#!/usr/bin/env python3

import sys
import argparse
import os
import regex
import se


def _output_file(chapter_number: int, header_xhtml: str, chapter_xhtml: str) -> None:
	"""
	Helper function to write a file given the chapter number, header XHTML, and chapter body XHTML.
	"""

	with open("chapter-" + str(chapter_number) + ".xhtml", "w", encoding="utf-8") as file:
		file.write(header_xhtml.replace("NUMBER", str(chapter_number)) + "\n" + chapter_xhtml + "\n</section></body></html>")
		file.truncate()

def main() -> int:
	parser = argparse.ArgumentParser(description="Split an XHTML file into many files at all instances of <!--se:split-->, and include a header template for each file.")
	parser.add_argument("filename", metavar="FILE", help="an XHTML file")
	args = parser.parse_args()

	with open(args.filename, "r", encoding="utf-8") as file:
		xhtml = se.strip_bom(file.read())

	with open(resource_filename("se", os.path.join("data", "templates", "header.xhtml")), "r", encoding="utf-8") as file:
		header_xhtml = file.read()

	chapter_number = 1
	chapter_xhtml = ""

	# Remove leading split tags
	xhtml = regex.sub(r"^\s*<\!--se:split-->", "", xhtml)

	for line in xhtml.splitlines():
		if "<!--se:split-->" in line:
			prefix, suffix = line.split("<!--se:split-->")
			chapter_xhtml = chapter_xhtml + prefix
			_output_file(chapter_number, header_xhtml, chapter_xhtml)

			chapter_number = chapter_number + 1
			chapter_xhtml = suffix

		else:
			chapter_xhtml = chapter_xhtml + "\n" + line

	if chapter_xhtml and not chapter_xhtml.isspace():
		_output_file(chapter_number, header_xhtml, chapter_xhtml)

	return 0


if __name__ == "__main__":
	sys.exit(main())
