#!/usr/bin/python

import argparse
import sys
from titlecase import titlecase

parser = argparse.ArgumentParser()
parser.add_argument("TEXT", help="Text to convert to title case", nargs="+")
parser.parse_args()

for argument in sys.argv[1:]:
	sys.stdout.write(titlecase(argument))
	
