#!/usr/bin/env python3

import argparse
import sys
import regex
from bs4 import BeautifulSoup
import se

def main():
	parser = argparse.ArgumentParser(description="Flatten a Standard Ebooks table of contents file to at most two levels deep for Kindle compatibility.")
	parser.add_argument("-v", "--verbose", action="store_true", help="increase output verbosity")
	parser.add_argument("filename", metavar="TOC-FILENAME", help="a Standard Ebooks table of contents file (typically toc.xhtml)")
	args = parser.parse_args()

	try:
		with open(args.filename, "r+", encoding="utf-8") as file:
			xhtml = file.read()

			soup = BeautifulSoup(xhtml, "lxml")

			for match in soup.select('ol > li > ol > li > ol'):
				match.unwrap()

			xhtml = str(soup)

			pattern = regex.compile(r"(<li>\s*<a href=\"[^\"]+?\">.+?</a>\s*)<li>", regex.MULTILINE)
			matches = 1
			while matches > 0:
				xhtml, matches = pattern.subn(r"\1</li><li>", xhtml)

			pattern = regex.compile(r"</li>\s*</li>", regex.MULTILINE)
			matches = 1
			while matches > 0:
				xhtml, matches = pattern.subn("</li>", xhtml)

			file.seek(0)
			file.write(xhtml)
			file.truncate()

	except Exception:
		se.print_error("Couldn't read file: {}".format(args.filename))
		exit(1)

if __name__ == "__main__":
	main()
