#!/usr/bin/env python3

import argparse
import re
from bs4 import BeautifulSoup

def main():
	parser = argparse.ArgumentParser(description="Flatten a Standard Ebooks table of contents file to at most two levels deep for Kindle compatibility.")
	parser.add_argument("-v", "--verbose", action="store_true", help="Increase output verbosity")
	parser.add_argument("tocFilename", metavar="TOC-FILENAME", help="A Standard Ebooks table of contents file (typically toc.xhtml)")
	args = parser.parse_args()

	with open(args.tocFilename, 'r+', encoding="utf-8") as file:
		text = file.read()
		file.seek(0)

		soup = BeautifulSoup(text, "lxml")

		for match in soup.select('ol > li > ol > li > ol'):
			match.unwrap()

		text = str(soup)

		r = re.compile(r'(<li>\s*<a href="[^"]+?">.+?</a>\s*)<li>', re.MULTILINE)
		matches = 1
		while matches > 0:
			text, matches = r.subn(r'\1</li><li>', text)

		r = re.compile(r'</li>\s*</li>', re.MULTILINE)
		matches = 1
		while matches > 0:
			text, matches = r.subn('</li>', text)

		file.write(text)
		file.truncate()

if __name__ == "__main__":
	main()
