#!/usr/bin/python3

import argparse
import sys
import unicodedata

parser = argparse.ArgumentParser()
parser.add_argument("UNICODESTRING", help="The Unicode string to display", nargs="+")
parser.parse_args()

for argument in sys.argv[1:]:
	for character in argument:
		print(character + "\tU+{:04X}".format(ord(character)) + "\t" + unicodedata.name(character) + "\t" + "http://unicode.org/cldr/utility/character.jsp?a={:04X}".format(ord(character)))
