#!/bin/sh
usage(){
	fmt <<EOF
DESCRIPTION
	Check all author directories in the current or specified directory to see if there are changes that need to be committed.

USAGE
	view-modified [DIRECTORY]
EOF
	exit
}
if [ $# -eq 1 ]; then if [ "$1" = "--help" -o "$1" = "-h" ]; then usage; fi fi
#End boilerplate

rootDir="$(pwd)"

if [ $# -eq 1 ]; then
	rootDir="$1"
fi

rootDir="$(cd -P "${rootDir}" && pwd)"

cd "${rootDir}"

for dir in "${rootDir}"/*/*/; do
	cd "${dir}"
	git status | grep "nothing to commit, working directory clean" > /dev/null
	if [ $? -ne 0 ]; then
		echo "${dir}"
		echo -n "\t"
		git status -s
		echo ""
	fi
done
