#!/usr/bin/env python3

import sys
import argparse
import se
import se.formatting


def main() -> int:
	parser = argparse.ArgumentParser(description="Count the number of words in an XHTML file and optionally categorize by length.  If multiple files are specified, show the total word count for all.")
	parser.add_argument("-c", "--categorize", action="store_true", help="include length categorization in output")
	parser.add_argument("-x", "--exclude-se-files", action="store_true", help="exclude some non-bodymatter files common to Standard Ebooks ebooks, like the ToC and colophon")
	parser.add_argument("targets", metavar="TARGET", nargs="+", help="an XHTML file, or a directory containing XHTML files")
	args = parser.parse_args()

	word_count = 0

	for filename in se.get_target_filenames(args.targets, (".xhtml"), args.exclude_se_files):
		if args.exclude_se_files and filename.endswith("endnotes.xhtml"):
			continue

		with open(filename, "r", encoding="utf-8") as file:
			word_count += se.formatting.get_word_count(file.read())

	if args.categorize:
		category = "se:short-story"
		if word_count > se.NOVELLA_MIN_WORD_COUNT and word_count < se.NOVEL_MIN_WORD_COUNT:
			category = "se:novella"
		elif word_count > se.NOVEL_MIN_WORD_COUNT:
			category = "se:novel"

	print("{}{}".format(word_count, "\t" + category if args.categorize else ""))

	return 0


if __name__ == "__main__":
	sys.exit(main())
