#!/usr/bin/python
# -*- coding: utf-8 -*-

import argparse
import sys
from bs4 import BeautifulSoup
import re

parser = argparse.ArgumentParser()
parser.add_argument("FILE", help="An HTML file to count the words of", nargs="+")
parser.parse_args()

for argument in sys.argv[1:]:
	fh = open(argument, "r")
	soup = BeautifulSoup(fh.read())
	fh.close()
	
	#This removes HTML tags
	body = soup.body.get_text()
	
	#Replace some formatting characters
	body = re.sub(ur"[…–—― ‘’“”\{\}\(\)]", " ", body, flags=re.UNICODE | re.IGNORECASE | re.DOTALL)
	
	#Remove word-connecting dashes, apostrophes, commas, and slashes (and/or), they count as a word boundry but they shouldn't
	body = re.sub(ur"[a-z0-9][\-\'\,\.\/][a-z0-9]", "aa", body, flags=re.UNICODE | re.IGNORECASE | re.DOTALL)
	
	#Replace sequential spaces with one space
	body = re.sub(ur"\s+", " ", body, flags=re.UNICODE | re.IGNORECASE | re.DOTALL)
	
	#Get the word count
	print(len(re.findall(ur"\b[a-z0-9]+\b", body, flags=re.UNICODE | re.IGNORECASE | re.DOTALL)))
