#!/usr/bin/env python3

import argparse
import sys
from bs4 import BeautifulSoup
import re

def main():
	parser = argparse.ArgumentParser(description="Count the number of words in an HTML file and optionally categorize by length.")
	parser.add_argument("-v", "--verbose", action="store_true", help="Include filename, wordcount, and length categorization in output")
	parser.add_argument("files", metavar="FILE", nargs="+", help="An HTML file to count the words of")
	args = parser.parse_args()

	for argument in args.files:
		fh = open(argument, "r")
		soup = BeautifulSoup(fh.read(), "lxml")
		fh.close()

		#This removes HTML tags
		body = soup.body.get_text()

		#Replace some formatting characters
		body = re.sub(r"[…–—― ‘’“”\{\}\(\)]", " ", body, flags=re.UNICODE | re.IGNORECASE | re.DOTALL)

		#Remove word-connecting dashes, apostrophes, commas, and slashes (and/or), they count as a word boundry but they shouldn't
		body = re.sub(r"[a-z0-9][\-\'\,\.\/][a-z0-9]", "aa", body, flags=re.UNICODE | re.IGNORECASE | re.DOTALL)

		#Replace sequential spaces with one space
		body = re.sub(r"\s+", " ", body, flags=re.UNICODE | re.IGNORECASE | re.DOTALL)

		#Get the word count
		wordCount = len(re.findall(r"\b[a-z0-9]+\b", body, flags=re.UNICODE | re.IGNORECASE | re.DOTALL))

		if args.verbose:
			#Categorize
			category = "se:short-story"
			if wordCount > 17500 and wordCount < 40000:
				category = "se:novella"
			elif wordCount > 40000:
				category = "se:novel"

			print(argument + "\t" + str(wordCount) + "\t" + category)
		else:
			print(str(wordCount))

if __name__ == "__main__":
	main()
