set -l se_commands british2american build build-images clean compare-versions create-draft dec2roman extract-ebook find-mismatched-diacritics help hyphenate interactive-sr lintmake-url-safe modernize-spelling prepare-release print-manifest-and-spine print-toc recompose-epub renumber-endnotesreorder-endnotes roman2dec semanticate split-file titlecasetypogrify unicode-names version word-count
complete -c se -a british2american -d "Try to convert British quote style to American quote style"
complete -c se -a build -d "Build an ebook from a Standard Ebook source directory"
complete -c se -a build-images -d "Build ebook cover and titlepage images in a Standard Ebook source directory"
complete -c se -a clean -d "Prettify and canonicalize individual XHTML or SVG files"
complete -c se -a compare-versions -d "Render and compare XHTML files in an ebook repository"
complete -c se -a create-draft -d "Create a skeleton of a new Standard Ebook"
complete -c se -a dec2roman -d "Convert a decimal number to a Roman numeral"
complete -c se -a extract-ebook -d "Extract an EPUB, MOBI, or AZW3 ebook"
complete -c se -a find-mismatched-diacritics -d "Find words with mismatched diacritics in Standard Ebook source directories"
complete -c se -a help -d "List available SE commands"
complete -c se -a hyphenate -d "Insert soft hyphens at syllable breaks in an XHTML file"
complete -c se -a interactive-sr -d "Use Vim to perform an interactive search and replace on a list of files"
complete -c se -a lint -d "Check for various Standard Ebooks style errors"
complete -c se -a make-url-safe -d "Make a string URL-safe"
complete -c se -a modernize-spelling -d "Modernize spelling of some archaic words, and replace words that may be archaically compounded with a dash to a more modern spelling"
complete -c se -a prepare-release -d "Calculate work word count, insert release date if not yet set, and update modified date and revision number"
complete -c se -a print-manifest-and-spine -d "Print <manifest> and <spine> tags to standard output for the given Standard Ebooks source directory"
complete -c se -a print-toc -d "Build a table of contents for an SE source directory and print to stdout"
complete -c se -a recompose-epub -d "Recompose a Standard Ebooks source directory into a single HTML5 file, and print to standard output"
complete -c se -a renumber-endnotes -d "Renumber all endnotes and noterefs sequentially from the beginning"
complete -c se -a reorder-endnotes -d "Increment the specified endnote and all following endnotes by 1"
complete -c se -a roman2dec -d "Convert a Roman numeral to a decimal number"
complete -c se -a semanticate -d "Apply some scriptable semantics rules from the Standard Ebooks semantics manual"
complete -c se -a split-file -d "Split an XHTML file into many files"
complete -c se -a titlecase -d "Convert a string to titlecase"
complete -c se -a typogrify -d "Apply some scriptable typography rules from the Standard Ebooks typography manual to a Standard Ebook source directory"
complete -c se -a unicode-names -d "Display Unicode code points, descriptions, and links to more details for each character in a string"
complete -c se -a version -d "Print the version number and exit"
complete -c se -a word-count -d "Count the number of words in an HTML file and optionally categorize by length"
