"""
This module implements the `se compare-versions` command.
"""

import argparse
import base64
from io import BytesIO
import shutil
import tempfile
from pathlib import Path
import importlib.resources
from typing import cast

from git import cmd
from natsort import natsorted
from PIL import Image, ImageChops
from PIL.Image import Image as Image_type
from selenium.common.exceptions import WebDriverException

import se
from se.se_help_formatter import SeHelpFormatter
from se.browser import Browser, BrowserType

# Disable PIL decompression bomb warnings for large images generated by diffs.
Image.MAX_IMAGE_PIXELS = None

def _resize_canvas(image: Image_type, new_width: int, new_height: int) -> Image_type:
	"""
	Expand an image's canvas with black, to the new height and width.
	"""
	temp_image = Image.new("RGBA", (new_width, new_height), (0, 0, 0, 255))
	temp_image.paste(image, (0, 0))

	return temp_image

def _screenshot_html_element(browser: 'Browser', filename: Path, output_path: Path) -> None:
	"""
	Load an XHTML file and save a screenshot of its full `<html>` element.
	"""

	browser.driver.get(filename.as_uri())

	wait_for_layout_script = """
		const callback = arguments[arguments.length - 1];
		const finish = () => requestAnimationFrame(() => requestAnimationFrame(callback));

		if(document.fonts && document.fonts.ready){
			document.fonts.ready.then(finish);
		}
		else{
			finish();
		}
	"""
	browser.driver.execute_async_script(wait_for_layout_script) # pyright: ignore[reportUnknownMemberType] Broken Selenium type hint here.

	# Chrome only screenshots the viewport, even when we specify the entire `<html>` element, so use special logic for Chrome.
	if browser.type == BrowserType.CHROME:
		_screenshot_chrome_full_page(browser, output_path)

	elif browser.type == BrowserType.FIREFOX:
		try:
			browser.driver.find_element("tag name", "html").screenshot(str(output_path)) # pyright: ignore Broken Selenium type hint here.
		except WebDriverException:
			# Firefox might throw an exception of the viewport is too large. In that case, fall back to a special function to stitch to together viewport-sized screenshots.
			_screenshot_firefox_or_safari_full_page(browser, output_path)

	# Safari needs to stitch together multiple screenshots to produce a full page image
	elif browser.type == BrowserType.SAFARI:
		_screenshot_firefox_or_safari_full_page(browser, output_path)

	else:
		raise se.MissingDependencyException("Couldn't initialize default web browser.")

def _screenshot_firefox_or_safari_full_page(browser: 'Browser', output_path: Path) -> None:
	"""
	Save a full-page Firefox or Safari screenshot by stitching together viewport-sized screenshots.
	"""

	get_dimensions_script = """
		return {
			width: document.documentElement.clientWidth,
			height: Math.max(document.documentElement.scrollHeight, document.body.scrollHeight),
			viewportWidth: window.innerWidth,
			viewportHeight: window.innerHeight
		};
	"""
	dimensions = cast(dict[str, int], browser.driver.execute_script(get_dimensions_script)) # pyright: ignore[reportUnknownMemberType] Broken Selenium type hint here.
	full_page_image = None

	for scroll_position in range(0, dimensions["height"], dimensions["viewportHeight"]):
		actual_scroll_position = cast(int, browser.driver.execute_script("window.scrollTo(0, arguments[0]); return window.scrollY;", scroll_position)) # pyright: ignore[reportUnknownMemberType] Broken Selenium type hint here.

		with Image.open(BytesIO(browser.driver.get_screenshot_as_png())) as viewport_image: # pyright: ignore[reportUnknownMemberType] Broken Selenium type hint here.
			scale = viewport_image.width / dimensions["viewportWidth"]
			full_width = round(dimensions["width"] * scale)
			full_height = round(dimensions["height"] * scale)
			paste_position = round(actual_scroll_position * scale)

			if full_page_image is None:
				full_page_image = Image.new("RGB", (full_width, full_height))

			tile_height = min(viewport_image.height, full_height - paste_position)
			full_page_image.paste(viewport_image.crop((0, 0, full_width, tile_height)), (0, paste_position))

	if full_page_image is not None:
		full_page_image.save(output_path)

def _screenshot_chrome_full_page(browser: 'Browser', output_path: Path) -> None:
	"""
	Save a full-page Chrome screenshot without changing the viewport size.

	We need this special function because Chrome always screenshots the viewport, even when we asked for a screenshot of the entire element.
	"""

	get_dimensions_script = """
		return {
			width: window.innerWidth,
			height: Math.max(document.documentElement.scrollHeight, document.body.scrollHeight)
		};
	"""
	dimensions = cast(dict[str, int], browser.driver.execute_script(get_dimensions_script)) # pyright: ignore[reportUnknownMemberType] Broken Selenium type hint here.

	screenshot_options: dict[str, str | bool | dict[str, float | bool]] = {
		"format": "png",
		"captureBeyondViewport": True,
		"fromSurface": True,
		"clip": {
			"x": 0,
			"y": 0,
			"width": float(dimensions["width"]),
			"height": float(dimensions["height"]),
			"scale": 1
		}
	}

	result = cast(dict[str, str], browser.driver.execute_cdp_cmd("Page.captureScreenshot", screenshot_options)) # pyright: ignore[reportUnknownMemberType] Broken Selenium type hint here.
	output_path.write_bytes(base64.b64decode(result["data"]))

def compare_versions(plain_output: bool) -> int:
	"""
	Entry point for `se compare-versions`.
	"""

	parser = argparse.ArgumentParser(description="Use a web browser to render and compare XHTML files in an ebook repository. Run on a dirty repository to visually compare the repository’s dirty state with its clean state. If a file renders differently, place screenshots of the new, original, and diff (if available) renderings in the current working directory. A file called [path]diff.html[/] is created to allow for side-by-side comparisons of original and new files.", prog="[command]se[/] [subcommand]compare-versions[/]", formatter_class=SeHelpFormatter)
	parser.add_argument("-i", "--include-se-files", dest="include_se_files", action="store_true", help="Include commonly-excluded Standard Ebooks files like imprint, titlepage, and colophon.")
	parser.add_argument("-n", "--no-images", dest="copy_images", action="store_false", help="Don’t create images of diffs.")
	parser.add_argument("-v", "--verbose", action="store_true", help="Increase output verbosity.")
	parser.add_argument("targets", metavar="[path]TARGET[/]", nargs="+", help="A directory containing XHTML files.")
	args = parser.parse_args()

	console = se.init_console()

	# We wrap this whole thing in a try block, because we need to quit the browser if execution is interrupted (like by `ctrl + c`, or by an unhandled exception). If we don't quit it, the browser will stay around as a zombie process even if the Python script is dead.
	browser = None
	try:
		browser = Browser()

		for target in args.targets:
			target = Path(target).resolve()

			if not target.is_dir():
				se.print_error(f"Target must be a directory: [path][link=file://{target}]{target}[/][/].", plain_output=plain_output)
				continue

			if args.verbose:
				console.print(se.prep_output(f"Processing [path][link=file://{target}]{target}[/][/] ...", plain_output))

			with tempfile.TemporaryDirectory(dir=browser.get_temporary_directory()) as work_directory_name:
				# Copy the Git repo to a temp folder, so we can stash and pop with impunity.
				shutil.copytree(target, work_directory_name, dirs_exist_ok=True)

				target_filenames: set[Path] = set()

				for file_path in Path(work_directory_name).glob("**/*.xhtml"):
					if not args.include_se_files:
						with open(file_path, "r", encoding="utf-8") as file:
							is_ignored, _ = se.get_dom_if_not_ignored(file.read())

						if not is_ignored:
							target_filenames.add(file_path)

					else:
						target_filenames.add(file_path)

				git_command = cmd.Git(work_directory_name)

				if "nothing to commit" in git_command.status():
					se.print_error("Repo is clean. This command must be run on a dirty repo.", args.verbose, plain_output=plain_output)
					continue

				output_directory = Path(f"./{target.name}_diff-output/")

				# Put Git's changes into the stash.
				git_command.stash()

				with tempfile.TemporaryDirectory() as temp_directory_name:
					# Generate screenshots of the pre-change repo.
					for filename in target_filenames:
						filename = Path(filename).resolve()

						if args.verbose:
							console.print(se.prep_output(f"\tProcessing original [path][link=file://{filename}]{filename.name}[/][/] ...", plain_output), end="")

						_screenshot_html_element(browser, filename, Path(temp_directory_name) / (filename.name + "-original.png"))

						if args.verbose:
							console.print(" done.")

					# Pop the stash.
					git_command.stash("pop")

					files_with_differences: set[Path] = set()

					# Generate screenshots of the post-change repo, and compare them to the old screenshots.
					for filename in target_filenames:
						filename = Path(filename).resolve()
						file_new_screenshot_path = Path(temp_directory_name) / (filename.name + "-new.png")
						file_original_screenshot_path = Path(temp_directory_name) / (filename.name + "-original.png")

						if args.verbose:
							console.print(se.prep_output(f"\tProcessing new [path][link=file://{filename}]{filename.name}[/][/] ...", plain_output), end="")

						_screenshot_html_element(browser, filename, file_new_screenshot_path)

						has_difference = False
						original_image_file = Image.open(file_original_screenshot_path)
						new_image_file = Image.open(file_new_screenshot_path)

						# Make sure the original and new images are the same size.
						# If they're not, add pixels in either direction until they match.
						original_width, original_height = original_image_file.size
						new_width, new_height = new_image_file.size
						target_width = max(original_width, new_width)
						target_height = max(original_height, new_height)
						new_image = new_image_file
						original_image = original_image_file

						if new_image_file.size != (target_width, target_height):
							new_image = _resize_canvas(new_image_file, target_width, target_height)
							new_image.save(file_new_screenshot_path)

						if original_image_file.size != (target_width, target_height):
							original_image = _resize_canvas(original_image_file, target_width, target_height)
							original_image.save(file_original_screenshot_path)

						# Now get the diff.
						diff = ImageChops.difference(original_image.convert("RGBA"), new_image.convert("RGBA"))

						# Process every pixel to see if there's a difference, and then convert that difference to red.
						if diff.convert("RGB").getbbox():
							width, height = diff.size
							for image_x in range(0, width - 1):
								for image_y in range(0, height - 1):
									if diff.getpixel((image_x, image_y)) != (0, 0, 0, 0):
										has_difference = True
										diff.putpixel((image_x, image_y), (255, 0, 0, 255)) # Change the mask color to red.

						if has_difference:
							files_with_differences.add(filename)

							if args.copy_images:
								try:
									output_directory.mkdir(parents=True, exist_ok=True)

									shutil.copy(file_new_screenshot_path, output_directory)
									shutil.copy(file_original_screenshot_path, output_directory)

									original_image_file.paste(diff.convert("RGB"), mask=diff)
									original_image_file.save(output_directory / (filename.name + "-diff.png"))

								except Exception:
									pass

						if args.verbose:
							console.print(" done.")

					for filename in natsorted(list(files_with_differences)):
						console.print(se.prep_output("{}Difference in {}".format("\t" if args.verbose else "", f"[path][link=file://{filename}]{filename.name}[/][/]."), plain_output))

					if files_with_differences and args.copy_images:
						# Generate an HTML file with diffs side by side.
						html = ""

						for filename in natsorted(list(files_with_differences)):
							html += f"\t\t<section>\n\t\t\t<h1>{filename.name}</h1>\n\t\t\t<img src=\"{filename.name}-original.png\">\n\t\t\t<img src=\"{filename.name}-new.png\">\n\t\t</section>\n"

						with importlib.resources.files("se.data.templates").joinpath("diff-template.html").open("r", encoding="utf-8") as file:
							html = file.read().replace("<!--se:sections-->", html.strip())

						with open(output_directory / "diff.html", "w", encoding="utf-8") as file:
							file.write(html)

	except se.MissingDependencyException as ex:
		se.print_error(ex)
		return ex.code

	except KeyboardInterrupt as ex:
		# Bubble the exception up, but proceed to `finally` so we quit the browser.
		raise ex

	finally:
		try:
			if browser:
				browser.driver.quit()
		except Exception:
			# We might get here if we `ctrl + c` before Selenium has finished initializing the driver.
			pass

	return 0
