name: Standard Ebooks toolset tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '>=3.10.12'
    - name: Install Ubuntu packages
      run: |
        sudo apt update
        sudo apt install calibre default-jre git python3-venv
    - name: Install pipx packages
      run: |
        pipx install .
        pipx inject standardebooks pylint==4.0.5 pyright==1.1.408 types-requests==2.32.4.20250913 types-setuptools==80.9.0.20250822 types-lxml==2026.2.16 pytest==9.0.2
    - name: Check type annotations with pyright
      run: $PIPX_HOME/venvs/standardebooks/bin/pyright --venvpath=$PIPX_HOME/venvs/ .
    - name: Check code with pylint
      run: $PIPX_HOME/venvs/standardebooks/bin/pylint .
    - name: Test with pytest
      run: $PIPX_HOME/venvs/standardebooks/bin/pytest
